# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server.port=8080
spring.servlet.multipart.enabled=true
logging.level.root=info
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
file.upload.max-allow-file-size=5368709120
file.upload.allowed-mime-list=
file.upload.forbidden-extension-list=
file.upload.dir=${user.dir}/uploads
file.upload.temp-dir=${user.dir}/uploads/temp
file.upload.buffer-size=2097152

